// export * from './dashboard/index'
// export * from './sendReceiveJasiri/index'
// export * from './tokens/Index'
// export * from './settings/index'
// export * from './wallet/index'
// export * from './registration/index'
// export * from './createAccount/index'
// export * from './HomePlaceHolder'

export * from './registration/index'
export * from './dashboard/Index'
export * from './sendReceiveJasiri/index'
export * from './tokens/Index'
export * from './settings//index'
export * from './wallet/Index'
export * from './createAccount/index'
export * from './HomePlaceHolder'
